### ISSUE TITLE
For the loss

### ISSUE THREAD

**Issue by stonewalking** [ilucasgoncalves/VAVL#9]
Hello Author,

How actually you calculated the train loss with the dimontional label type, i see there is only dev loss and test loss?
Why is the reason, you don't use train loss, is it because of the reconstructed loss?
And when i followed the same loss simply add train = 3.0 -a -v -d. And train with 20 epochs.
It is weird that test loss is lower than train loss, and dev loss is unchange and is the higher than train.

Is there any bug i guess in your cccloss  script in "untils" ?

Thanks

**Comment by ilucasgoncalves** [comment]
I think I found the issue. When I updated the code to upload to github I included code in the /utils/data_manager.py a function that would automatically handle an error on the MSP-IMPROV dataset annotation that the values for the rating scale of arousal (1 to 5) were actually flipped when this dataset was annotated (5 to 1).

however, the provided consensus files for improv already handles this labeling issue from the dataset. Therefore flipping the arousal signs again actually messes up the loss calculation. 

I updated the /utils/data_manager.py to removed the duplicate flipping. This should solve the issues and the train, test, and dev loss should look better now

**Comment by stonewalking** [comment]
Hello author, 

I tried with your updated version, but there still sames have a gap between dev and test in the loss-epoch plotted picture, i am wondering is it because when you splite the train and dev test set in the csv file not being totally random?

**Comment by stonewalking** [comment]
> Hello author,
> 
> I tried with your updated version, but there still sames have a gap between dev and test in the loss-epoch plotted picture, i am wondering is it because when you splite the train and dev test set in the csv file not being totally random?

although the shape looks good, but it is still not have a deep gap between test and dev losses

**Comment by ilucasgoncalves** [comment]
What you mean by not totally random? The sets cannot be entirely randomized since we do not want to mix speakers across different sets. We need speaker independent sets, so we randomized based on speakers.

I will pull this code and run a test against the uncleaned version. Maybe there could be some other bug in the code that i introduced when cleaning code for github upload.

FYI: we'll me moving this repo soon to our labs https://github.com/MSP-UTD
